const tarotDeck = [
    "The World",
    "Judgement",
    "The Sun",
    "The Moon",
    "The Star",
    "The Tower",
    "The Devil",
    "Temperance",
    "Death",
    "The Hanged Man",
    "Justice",
    "The Wheel of Fortune",
    "The Hermit",
    "Strength",
    "The Chariot",
    "The Lovers",
    "The Heirophant",
    "The Emperor",
    "The Empress",
    "The High Priestess",
    "The Magician",
    "The Fool",
    "Seven of Wands",
    "Four of Wands",
    "Ace of Wands",
    "Ten of Wands",
    "Nine of Wands",
    "Eight of Wands",
    "Six of Wands",
    "Five of Wands",
    "Three of Wands",
    "Two of Wands",
    "Page of Wands",
    "Queen of Wands",
    "King of Wands",
    "Knight of Wands",
    "King of Cups",
    "Queen of Cups",
    "Knight of Cups",
    "Page of Cups",
    "Ten of Cups",
    "Nine of Cups",
    "Eight of Cups",
    "Seven of Cups",
    "Six of Cups",
    "Five of Cups",
    "Four of Cups",
    "Three of Cups",
    "Two of Cups",
    "Ace of Cups",
    "King of Swords",
    "Knight of Swords",
    "Queen of Swords",
    "Page of Swords",
    "Ten of Swords",
    "Nine of Swords",
    "Eight of Swords",
    "Seven of Swords",
    "Six of Swords",
    "Five of Swords",
    "Three of Swords",
    "Four of Swords",
    "Two of Swords",
    "Ace of Swords",
    "King of Pentacles",
    "Queen of Pentacles",
    "Knight of Pentacles",
    "Page of Pentacles",
    "Ten of Pentacles",
    "Nine of Pentacles",
    "Eight of Pentacles",
    "Seven of Pentacles",
    "Six of Pentacles",
    "Five of Pentacles",
    "Four of Pentacles",
    "Three of Pentacles",
    "Two of Pentacles",
    "Ace of Pentacles"
]

export default tarotDeck